const dict = {
  es: {
    title1: 'HANNA IN',
    title2: 'MIDDLE EARTH',
    play: 'JUGAR',
    soon: '¡Pronto!',
    again: 'OTRA VEZ',
    home: 'INICIO',
    win: '¡LO LOGRASTE!',
    settings: 'Ajustes',
    sound: 'Sonido',
    language: 'Idioma',
    players: 'Jugadores',
    whoPlays: '¿Quiénes juegan?',
    start: '¡EMPEZAR!',
    pairs: 'Parejas',
    winner: '¡Ganó {name}!',
    winTeam: '¡Equipo victorioso!',
    chars: {
      mascot: 'Hobbit',
      creature: 'Criatura',
      gandalf: 'Mago',
      dwarf: 'Enano',
      elf: 'Elfo',
    },
    memory: {
      title: 'Memoria de la Comarca',
      desc: 'Encuentra las parejas escondidas tras las puertas redondas.',
      how: 'Toca dos puertas.\n¡Encuentra todas las parejas!',
    },
    riddles: {
      title: 'Acertijos en la Oscuridad',
      desc: 'Responde acertijos para escapar de la cueva.',
      how: 'Lee el acertijo.\n¡Toca la respuesta correcta!',
    },
    tokens: {
      mountain: 'Montaña',
      tree: 'Árbol',
      dragon: 'Dragón',
      egg: 'Huevo',
      mushroom: 'Hongo',
      barrel: 'Barril',
      fish: 'Pez',
      spider: 'Araña',
      wind: 'Viento',
      ring: 'Anillo',
      sword: 'Espada',
      wizard: 'Mago',
      moon: 'Luna',
      sun: 'Sol',
      candle: 'Vela',
      key: 'Llave',
      star: 'Estrella',
      gem: 'Gema',
      door: 'Puerta',
      eagle: 'Águila',
      honey: 'Miel',
      troll: 'Trol',
    },
    barrels: {
      title: 'Carrera de Barriles',
      desc: 'Esquiva las rocas río abajo dentro de un barril.',
      how: 'Toca un carril para moverte\ny esquiva las rocas.\n¡El primero en llegar al lago gana!\n(1 o 2 jugadores)',
    },
    sharedbarrel: {
      title: 'Barril Compartido',
      desc: 'Un barril, dos timones: esquiven juntos rocas y troncos.',
      how: 'Uno mueve el barril de lado (rocas),\nel otro lo mueve de cerca a lejos (troncos).\n¡Avísense el peligro!\n(2 jugadores)',
    },
    breakfast: {
      title: 'Segundo Desayuno',
      desc: 'Sirve el plato correcto antes que se acabe el tiempo.',
      how: 'Mira lo que pide cada hobbit\ny toca el plato correcto.\n¡El más rápido gana!\n(2 jugadores)',
    },
    tug: {
      title: 'Tira y Afloja',
      desc: '¡Machaca el botón y arrastra al trol a tu lado!',
      how: '¡Toca rapidísimo!\nArrastra al trol hasta tu barro.\n(2 jugadores, uno frente al otro)',
      ready: '¿Listos?',
      go: '¡YA!',
      round: '¡Ronda para {name}!',
    },
    dragon: {
      title: '¡El Dragón Despierta!',
      desc: 'Duelo de reflejos: toca primero cuando abra los ojos.',
      how: 'Cuando el dragón abra los ojos…\n¡toca tu botón primero!\n(2 jugadores, uno frente al otro)',
      sleep: 'Shhh… duerme',
      now: '¡AHORA!',
      early: '¡Aún duerme!',
      gem: '¡Gema para {name}!',
    },
    sneak: {
      title: 'El Trol Dormido',
      desc: 'De puntillas los dos juntos: róbenle las gemas al trol.',
      how: 'Cuando brille verde…\n¡toquen los dos a la vez!\nSi el trol se mueve, esperen.\n(2 jugadores, uno frente al otro)',
      wait: 'Shhh… esperen',
      now: '¡AHORA, JUNTOS!',
      good: '¡Bien!',
      together: '¡Toca tú también!',
      shh: '¡Shhh! Casi despierta',
      miss: '¡Juntos a la vez!',
      got: '¡Gema robada!',
    },
    treasure: {
      title: 'El Tesoro de Erebor',
      desc: 'Guarden juntos los tesoros en el cofre, con calma.',
      how: 'Miren qué pide el cofre\ny toquen ese tesoro.\nSe turnan: ¡equipo!\n(2 jugadores, sin prisa)',
      turn: 'Turno de {name}',
      full: '¡Cofre lleno!',
    },
    shire: {
      title: 'Defender la Comarca',
      desc: '¡Espanten a las arañas antes de que lleguen a la puerta!',
      how: 'Cada uno defiende su lado:\ntoquen las arañas para espantarlas.\n¡Cuiden la puerta entre los dos\nhasta el amanecer!\n(2 jugadores a la vez)',
      dawn: '¡Amaneció!',
      failTitle: '¡Ay, el jardín!',
      failDesc: 'Las arañas llegaron a la puerta.\n¡Inténtenlo de nuevo!',
    },
    beacons: {
      title: 'El Faro de Gondor',
      desc: 'Enciendan la cadena de faros antes de que la señal se apague.',
      how: 'Cuando la chispa llegue a tu hoguera,\n¡tócala antes de que se encoja el anillo!\nSe turnan: uno, luego el otro.\n(2 jugadores)',
    },
    secrettree: {
      title: 'El Árbol de los Secretos',
      desc: 'Cada quien ve la mitad del árbol. ¡Descríbanse lo que ven!',
      how: 'Tú ves tus símbolos, tu compañero ve los suyos.\nDescríbanselos en voz alta\ny toquen los que hacen pareja.\n(2 jugadores, uno frente al otro, ya deben hablar bien)',
    },
    clearing: {
      title: 'El Sendero de la Comarca',
      desc: 'Camina hasta la puerta, esquivando o espantando arañas.',
      how: 'Arrastra el círculo para caminar.\nToca una araña para espantarla,\no simplemente rodéala.\n¡Llega hasta la puerta!\n(1 jugador)',
    },
    journey: {
      title: 'El Gran Viaje',
      desc: 'Un juego de mesa hasta la Montaña Solitaria.',
      how: 'Lanza el dado y viaja\nhasta la Montaña Solitaria.',
      roll: 'LANZAR',
      go: '¡VAMOS!',
      rollHint: '¡Toca para lanzar!',
      whoPlays: '¿Quiénes viajan?',
      start: '¡EMPEZAR!',
      turn: 'Turno de {name}',
      modeTitle: '¿Cómo quieren jugar?',
      modeHint: 'Carrera: gana quien llegue primero.\nEquipo: viajen juntos... ¡cuidado con el humo de Smaug!',
      modeRace: 'CARRERA',
      modeTeam: 'EQUIPO',
      smokeTitle: '¡Casi lo logran!',
      smokeDesc: 'El humo de Smaug los alcanzó\njusto antes de llegar.\n¡Inténtenlo de nuevo!',
      zones: ['La Comarca', 'Rivendel', 'Las Montañas', 'Tierras de Beorn', 'Bosque Negro', ''],
      places: {
        trolls: '¡Trolls!',
        rivendell: 'Rivendel',
        storm: 'Montañas Nubladas',
        cave: 'La Cueva',
        eagles: 'Las Águilas',
        beorn: 'Casa de Beorn',
        spiders: 'Bosque Negro',
        barrels: 'El Río',
        laketown: 'Ciudad del Lago',
      },
      events: {
        trolls: '¡Trolls hambrientos!\n¡Corre 2 casillas atrás!',
        rivendell: 'Los elfos te regalan pan élfico.\n¡Avanza 2!',
        storm: '¡Tormenta en las montañas!\nRetrocede 1.',
        cave: 'Tu amigo de la cueva\nte enseña un atajo. ¡Avanza 1!',
        eagles: '¡Las águilas te llevan volando!\n¡Avanza 3!',
        beorn: 'Pasteles de miel en casa de Beorn.\n¡Avanza 2!',
        spiders: '¡Arañas en el bosque!\nRetrocede 2.',
        barrels: '¡Escape en barriles por el río!\n¡Avanza 2!',
        laketown: 'La Ciudad del Lago te recibe\ncon una fiesta. ¡Avanza 1!',
      },
    },
  },
  en: {
    title1: 'HANNA IN',
    title2: 'MIDDLE EARTH',
    play: 'PLAY',
    soon: 'Soon!',
    again: 'AGAIN',
    home: 'HOME',
    win: 'YOU DID IT!',
    settings: 'Settings',
    sound: 'Sound',
    language: 'Language',
    players: 'Players',
    whoPlays: 'Who is playing?',
    start: 'START!',
    pairs: 'Pairs',
    winner: '{name} wins!',
    winTeam: 'Team victory!',
    chars: {
      mascot: 'Hobbit',
      creature: 'Creature',
      gandalf: 'Wizard',
      dwarf: 'Dwarf',
      elf: 'Elf',
    },
    memory: {
      title: 'Shire Memory',
      desc: 'Find the pairs hidden behind the round doors.',
      how: 'Tap two doors.\nFind all the pairs!',
    },
    riddles: {
      title: 'Riddles in the Dark',
      desc: 'Answer riddles to escape the cave.',
      how: 'Read the riddle.\nTap the right answer!',
    },
    tokens: {
      mountain: 'Mountain',
      tree: 'Tree',
      dragon: 'Dragon',
      egg: 'Egg',
      mushroom: 'Mushroom',
      barrel: 'Barrel',
      fish: 'Fish',
      spider: 'Spider',
      wind: 'Wind',
      ring: 'Ring',
      sword: 'Sword',
      wizard: 'Wizard',
      moon: 'Moon',
      sun: 'Sun',
      candle: 'Candle',
      key: 'Key',
      star: 'Star',
      gem: 'Gem',
      door: 'Door',
      eagle: 'Eagle',
      honey: 'Honey',
      troll: 'Troll',
    },
    barrels: {
      title: 'Barrel Run',
      desc: 'Dodge the rocks down the river inside a barrel.',
      how: 'Tap a lane to move\nand dodge the rocks.\nFirst to reach the lake wins!\n(1 or 2 players)',
    },
    sharedbarrel: {
      title: 'Shared Barrel',
      desc: 'One barrel, two helms: dodge rocks and logs together.',
      how: 'One steers side to side (rocks),\nthe other steers near to far (logs).\nCall out the danger!\n(2 players)',
    },
    breakfast: {
      title: 'Second Breakfast',
      desc: 'Serve the right plate before time runs out.',
      how: 'See what each hobbit wants\nand tap the right plate.\nFastest server wins!\n(2 players)',
    },
    tug: {
      title: 'Tug of War',
      desc: 'Mash the button and drag the troll to your side!',
      how: 'Tap as fast as you can!\nDrag the troll into your mud.\n(2 players, face to face)',
      ready: 'Ready?',
      go: 'GO!',
      round: 'Round for {name}!',
    },
    dragon: {
      title: 'The Dragon Wakes!',
      desc: 'Reflex duel: tap first when it opens its eyes.',
      how: 'When the dragon opens its eyes…\ntap your button first!\n(2 players, face to face)',
      sleep: 'Shhh… sleeping',
      now: 'NOW!',
      early: 'Still sleeping!',
      gem: 'Gem for {name}!',
    },
    sneak: {
      title: 'The Sleeping Troll',
      desc: "Tiptoe together and steal the troll's gems.",
      how: 'When it glows green…\ntap at the same time!\nIf the troll stirs, wait.\n(2 players, face to face)',
      wait: 'Shhh… wait',
      now: 'NOW, TOGETHER!',
      good: 'Nice!',
      together: 'You tap too!',
      shh: 'Shhh! It almost woke up',
      miss: 'Tap at the same time!',
      got: 'Gem stolen!',
    },
    treasure: {
      title: 'The Treasure of Erebor',
      desc: 'Calmly tuck the treasures into the chest together.',
      how: 'See what the chest asks for\nand tap that treasure.\nTake turns — teamwork!\n(2 players, no rush)',
      turn: "{name}'s turn",
      full: 'Chest full!',
    },
    shire: {
      title: 'Defend the Shire',
      desc: 'Shoo the spiders before they reach the door!',
      how: 'Each of you guards one side:\ntap the spiders to shoo them away.\nProtect the door together\nuntil sunrise!\n(2 players at once)',
      dawn: 'Sunrise!',
      failTitle: 'Oh no, the garden!',
      failDesc: 'The spiders reached the door.\nTry again!',
    },
    beacons: {
      title: 'The Beacon of Gondor',
      desc: 'Light the chain of beacons before the signal fades.',
      how: "When the spark reaches your bonfire,\ntap it before the ring shrinks away!\nTake turns: one, then the other.\n(2 players)",
    },
    secrettree: {
      title: 'The Tree of Secrets',
      desc: "You each see half the tree. Describe what you see to each other!",
      how: "You see your symbols, your partner sees theirs.\nDescribe them out loud\nand tap the ones that match.\n(2 players, face to face, needs some talking)",
    },
    clearing: {
      title: 'The Shire Path',
      desc: 'Walk to the gate, dodging or shooing spiders along the way.',
      how: 'Drag the circle to walk.\nTap a spider to shoo it away,\nor just walk around it.\nReach the gate!\n(1 player)',
    },
    journey: {
      title: 'The Great Journey',
      desc: 'A board game all the way to the Lonely Mountain.',
      how: 'Roll the die and travel\nto the Lonely Mountain.',
      roll: 'ROLL',
      go: "LET'S GO!",
      rollHint: 'Tap to roll!',
      whoPlays: 'Who is traveling?',
      start: 'START!',
      turn: "{name}'s turn",
      modeTitle: 'How do you want to play?',
      modeHint: "Race: first to arrive wins.\nTeam: travel together... watch out for Smaug's smoke!",
      modeRace: 'RACE',
      modeTeam: 'TEAM',
      smokeTitle: 'So close!',
      smokeDesc: "Smaug's smoke caught up\nright before you arrived.\nTry again!",
      zones: ['The Shire', 'Rivendell', 'The Mountains', "Beorn's Lands", 'Mirkwood', ''],
      places: {
        trolls: 'Trolls!',
        rivendell: 'Rivendell',
        storm: 'Misty Mountains',
        cave: 'The Cave',
        eagles: 'The Eagles',
        beorn: "Beorn's House",
        spiders: 'Mirkwood',
        barrels: 'The River',
        laketown: 'Lake-town',
      },
      events: {
        trolls: 'Hungry trolls!\nRun 2 tiles back!',
        rivendell: 'The elves give you elf-bread.\nMove 2 ahead!',
        storm: 'Storm in the mountains!\nGo back 1.',
        cave: 'Your cave friend\nshows you a shortcut. Move 1 ahead!',
        eagles: 'The eagles carry you!\nFly 3 ahead!',
        beorn: "Honey cakes at Beorn's house.\nMove 2 ahead!",
        spiders: 'Spiders in the forest!\nGo back 2.',
        barrels: 'Barrel ride down the river!\nMove 2 ahead!',
        laketown: 'Lake-town throws you a party!\nMove 1 ahead!',
      },
    },
  },
};

export let lang = localStorage.getItem('lme-lang') || 'es';

export function setLang(l) {
  lang = dict[l] ? l : 'es';
  localStorage.setItem('lme-lang', lang);
}

export function t(path) {
  let cur = dict[lang];
  for (const part of path.split('.')) cur = cur?.[part];
  return cur ?? path;
}
